"""Popularity baselines: simple recommenders the two-tower model has to beat.

Usage:
    python -m src.models.baselines

Reads the feature tables (run src.features.build_features first), scores each baseline on
the test week and writes reports/baselines.json and reports/baselines.md.

    global_popularity      the best-sellers of the last training week, for everyone
    age_group_popularity   the best-sellers among customers of the same age band
    repurchase             the customer's own most-bought products, then the best-sellers
"""

import json
import sys
from collections.abc import Sequence

import pandas as pd

from src.config import load_config, project_path
from src.models.metrics import evaluate


def top_articles(transactions: pd.DataFrame, n: int) -> list[str]:
    """The n most-bought articles (by units), ties broken by article ID."""
    units = transactions.groupby("article_id")["quantity"].sum().reset_index()
    units = units.sort_values(["quantity", "article_id"], ascending=[False, True])
    return units["article_id"].head(n).tolist()


def fill_up(first: Sequence[str], rest: Sequence[str], n: int) -> list[str]:
    """first, then items from rest that are not already in it, up to n items."""
    seen = set(first)
    return (list(first) + [item for item in rest if item not in seen])[:n]


def global_popularity(last_week: pd.DataFrame, customers: Sequence[str], n: int) -> dict[str, list[str]]:
    best = top_articles(last_week, n)
    return {customer: best for customer in customers}


def age_group_popularity(
    last_week: pd.DataFrame, users: pd.DataFrame, customers: Sequence[str], n: int
) -> dict[str, list[str]]:
    best = top_articles(last_week, n)
    with_age = last_week.merge(users[["customer_id", "age_bucket"]], on="customer_id")
    by_group = {
        group: fill_up(top_articles(rows, n), best, n)
        for group, rows in with_age.groupby("age_bucket")
    }
    bucket_of = users.set_index("customer_id")["age_bucket"]
    return {customer: by_group.get(bucket_of.get(customer), best) for customer in customers}


def repurchase(
    window: pd.DataFrame, last_week: pd.DataFrame, customers: Sequence[str], n: int
) -> dict[str, list[str]]:
    """Each customer's own articles (most units first, then most recent), then best-sellers."""
    best = top_articles(last_week, n)
    own = (
        window.groupby(["customer_id", "article_id"])
        .agg(units=("quantity", "sum"), last=("t_dat", "max"))
        .reset_index()
        .sort_values(["customer_id", "units", "last"], ascending=[True, False, False])
        .groupby("customer_id")["article_id"].agg(list)
    )
    return {customer: fill_up(own.get(customer, [])[:n], best, n) for customer in customers}


def to_markdown(results: dict[str, dict], k_values: Sequence[int]) -> str:
    metrics = [f"recall@{k}" for k in k_values] + ["ndcg@12", "map@12"]
    lines = [
        "# Baseline results",
        "",
        "Simple recommenders scored on the test week. The two-tower model has to beat these.",
        "Generated by `python -m src.models.baselines`.",
        "",
    ]
    for group in ("all", "warm", "cold"):
        customers = next(iter(results.values()))[group]["customers"]
        lines += [f"## {group.capitalize()} customers ({customers:,})", "",
                  "| Baseline | " + " | ".join(metrics) + " |",
                  "|---|" + "---|" * len(metrics)]
        for name, scores in results.items():
            lines.append(f"| {name} | " + " | ".join(f"{scores[group][m]:.4f}" for m in metrics) + " |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    config = load_config()
    processed = project_path(config["paths"]["processed_dir"])
    if not (processed / "test").is_dir():
        print("Feature tables not found. Run: python -m src.features.build_features", file=sys.stderr)
        return 1

    k_values = config["evaluation"]["k_values"]
    n = max(k_values)
    summary = json.loads((processed / "features_summary.json").read_text(encoding="utf-8"))
    first_week, last_week = summary["training_weeks"]

    columns = ["customer_id", "article_id", "t_dat", "quantity"]
    window = pd.read_parquet(processed / "transactions", columns=columns,
                             filters=[("week", ">=", first_week), ("week", "<=", last_week)])
    final_week = pd.read_parquet(processed / "transactions", columns=columns,
                                 filters=[("week", "==", last_week)])
    users = pd.read_parquet(processed / "user_features", columns=["customer_id", "age_bucket"])
    test = pd.read_parquet(processed / "test")
    customers = test["customer_id"].tolist()

    recommenders = {
        "global_popularity": lambda: global_popularity(final_week, customers, n),
        "age_group_popularity": lambda: age_group_popularity(final_week, users, customers, n),
        "repurchase": lambda: repurchase(window, final_week, customers, n),
    }
    results = {}
    for name, recommend in recommenders.items():
        print(f"Scoring {name} ...")
        results[name] = evaluate(recommend(), test, k_values)

    reports = project_path("reports")
    reports.mkdir(exist_ok=True)
    (reports / "baselines.json").write_text(json.dumps(results, indent=2), encoding="utf-8")
    (reports / "baselines.md").write_text(to_markdown(results, k_values), encoding="utf-8")
    print(to_markdown(results, k_values))
    return 0


if __name__ == "__main__":
    sys.exit(main())
