"""Score a trained two-tower model on the test week and compare it with the baselines.

Usage:
    python -m src.models.evaluate                  # the newest model in models/
    python -m src.models.evaluate --version v1

For every test customer, the query tower makes a customer vector, and the top 100 products
by dot product are taken from the products sold in the last few weeks before the cut-off
(evaluation.candidate_weeks in the config). Three results are reported:
    two_tower               the model for every customer
    two_tower + fallback    the model for warm customers, age-group best-sellers for cold ones
                            (the serving strategy from the blueprint)
    repurchase + two_tower  the customer's own past products first, then the model's

Writes models/<version>/metrics.json and reports/evaluation_<version>.md.
"""

import argparse
import json
import sys

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

from src.config import load_config, project_path
from src.features.vocab import load_vocabularies
from src.models.baselines import age_group_popularity, fill_up, own_purchases
from src.models.dataset import encode_candidates, encode_queries, load_candidate_items, load_test_queries
from src.models.metrics import evaluate
from src.models.train import WEIGHTS_FILE, build_model
from src.models.two_tower import tf

QUERY_BATCH = 1024


def latest_version(models_dir) -> str:
    versions = sorted(p.name for p in models_dir.iterdir() if (p / "training.json").exists())
    if not versions:
        raise FileNotFoundError(f"No trained model in {models_dir}. Run: python -m src.models.train")
    return versions[-1]


def in_batches(tower, inputs: dict[str, np.ndarray], size: int) -> np.ndarray:
    rows = len(next(iter(inputs.values())))
    return np.concatenate([
        tower({name: values[start:start + size] for name, values in inputs.items()}).numpy()
        for start in range(0, rows, size)
    ])


def top_k(query_vectors: np.ndarray, item_vectors: np.ndarray, item_ids: np.ndarray, k: int) -> list[list[str]]:
    """The k highest-scoring items for each query (exact search; FAISS replaces it in Week 3)."""
    items = tf.constant(item_vectors)
    results = []
    for start in range(0, len(query_vectors), QUERY_BATCH):
        scores = tf.linalg.matmul(query_vectors[start:start + QUERY_BATCH], items, transpose_b=True)
        best = tf.math.top_k(scores, k=k).indices.numpy()
        results.extend(item_ids[best].tolist())
    return results


def to_markdown(version: str, results: dict[str, dict], baselines: dict[str, dict], k_values,
                candidate_weeks: int, n_candidates: int) -> str:
    metrics = [f"recall@{k}" for k in k_values] + ["ndcg@12", "map@12"]
    rows = {**baselines, **results}
    lines = [
        f"# Evaluation: model {version}",
        "",
        "Test week: the final week of the dataset. Generated by `python -m src.models.evaluate`.",
        f"The model ranks the {n_candidates:,} products sold in the last {candidate_weeks} week(s) "
        "before the cut-off.",
        "Baselines come from `reports/baselines.json`.",
        "",
    ]
    for group in ("all", "warm", "cold"):
        customers = next(iter(results.values()))[group]["customers"]
        lines += [f"## {group.capitalize()} customers ({customers:,})", "",
                  "| Recommender | " + " | ".join(metrics) + " |",
                  "|---|" + "---|" * len(metrics)]
        for name, scores in rows.items():
            label = f"**{name}**" if name in results else name
            lines.append(f"| {label} | " + " | ".join(f"{scores[group][m]:.4f}" for m in metrics) + " |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--version")
    parser.add_argument("--candidate-weeks", type=int, help="override evaluation.candidate_weeks")
    args = parser.parse_args()

    config = load_config()
    processed = project_path(config["paths"]["processed_dir"])
    models_dir = project_path(config["paths"]["models_dir"])
    version = args.version or latest_version(models_dir)
    model_dir = models_dir / version
    k_values = config["evaluation"]["k_values"]
    k = max(k_values)

    vocabularies = load_vocabularies(model_dir / "vocab")
    model = build_model(vocabularies, config)

    print("Encoding products and test customers ...")
    candidate_weeks = args.candidate_weeks or config["evaluation"]["candidate_weeks"]
    items = load_candidate_items(processed, candidate_weeks)
    candidates = encode_candidates(items, vocabularies, config["features"]["popularity_weeks"])
    queries_table = load_test_queries(processed, config["features"]["max_days_since"])
    queries = encode_queries(queries_table, vocabularies, config["model"]["history_length"])

    # Run both towers once so the layers exist, then load the trained weights into them.
    model.query_tower({name: values[:1] for name, values in queries.items()})
    model.candidate_tower({name: values[:1] for name, values in candidates.items()})
    model.load_weights(str(model_dir / WEIGHTS_FILE)).expect_partial()

    print(f"Scoring {len(queries_table):,} customers against {len(items):,} products ...")
    item_vectors = in_batches(model.candidate_tower, candidates, 8192)
    query_vectors = in_batches(model.query_tower, queries, 8192)
    item_ids = np.asarray(items["article_id"].to_pylist())
    customers = queries_table["customer_id"].to_pylist()
    model_recs = dict(zip(customers, top_k(query_vectors, item_vectors, item_ids, k)))

    test = pd.read_parquet(processed / "test")
    summary = json.loads((processed / "features_summary.json").read_text(encoding="utf-8"))
    first_week, last_week = summary["training_weeks"]
    columns = ["customer_id", "article_id", "t_dat", "quantity"]
    window = pd.read_parquet(processed / "transactions", columns=columns,
                             filters=[("week", ">=", first_week), ("week", "<=", last_week)])
    final_week = pd.read_parquet(processed / "transactions", columns=columns,
                                 filters=[("week", "==", last_week)])
    users = pq.read_table(processed / "user_features", columns=["customer_id", "age_bucket"]).to_pandas()
    fallback = age_group_popularity(final_week, users, customers, k)
    cold = set(test.loc[test["is_cold_start"] == 1, "customer_id"])
    combined = {c: fallback[c] if c in cold else model_recs[c] for c in customers}
    own = own_purchases(window)
    blended = {c: fill_up(own.get(c, [])[:k], model_recs[c], k) for c in customers}

    results = {
        "two_tower": evaluate(model_recs, test, k_values),
        "two_tower + fallback": evaluate(combined, test, k_values),
        "repurchase + two_tower": evaluate(blended, test, k_values),
    }
    (model_dir / "metrics.json").write_text(json.dumps(results, indent=2), encoding="utf-8")

    baselines_path = project_path("reports") / "baselines.json"
    baselines = json.loads(baselines_path.read_text(encoding="utf-8")) if baselines_path.exists() else {}
    report = to_markdown(version, results, baselines, k_values, candidate_weeks, len(items))
    (project_path("reports") / f"evaluation_{version}.md").write_text(report, encoding="utf-8")
    print(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
